"""create skills lessons exercises user_skill_progress tables

Revision ID: 772d3af2a112
Revises: bc3acb0ae17a
Create Date: 2026-09-16 00:14:21.792458

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "772d3af2a112"
down_revision: str | Sequence[str] | None = "bc3acb0ae17a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_index", name="uq_skills_order_index"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "order_index", name="uq_lessons_skill_order"),
    )
    op.create_index("ix_lessons_skill_id", "lessons", ["skill_id"], unique=False)
    op.create_table(
        "user_skill_progress",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("unlocked", sa.Boolean(), nullable=False),
        sa.Column("crown_level", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "crown_level >= 0 AND crown_level <= 5", name="ck_user_skill_progress_crown_level"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_user_skill_progress_user_skill"),
    )
    op.create_index(
        "ix_user_skill_progress_user_id", "user_skill_progress", ["user_id"], unique=False
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("answer_key", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "type IN ('multiple_choice', 'listening', 'sentence_construction')",
            name="ck_exercises_type",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "order_index", name="uq_exercises_lesson_order"),
    )
    op.create_index("ix_exercises_lesson_id", "exercises", ["lesson_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_exercises_lesson_id", table_name="exercises")
    op.drop_table("exercises")
    op.drop_index("ix_user_skill_progress_user_id", table_name="user_skill_progress")
    op.drop_table("user_skill_progress")
    op.drop_index("ix_lessons_skill_id", table_name="lessons")
    op.drop_table("lessons")
    op.drop_table("skills")
    # ### end Alembic commands ###
