// A palette with a different colour in every role, for tests that check a
// widget draws from the palette it is given (022-light-and-dark-themes).

import 'package:elang/shared/theme/app_palette.dart';
import 'package:flutter/painting.dart';

/// A palette in which every role has its own colour, so a piece that reads
/// the wrong role, or the light palette, is caught.
AppPalette distinctPalette() {
  var n = 0;
  Color next() => Color(0xFF000000 + (++n) * 0x010203);
  return AppPalette(
    surface: next(),
    surfaceDim: next(),
    surfaceContainerLowest: next(),
    surfaceContainerLow: next(),
    surfaceContainer: next(),
    surfaceContainerHigh: next(),
    surfaceContainerHighest: next(),
    onSurface: next(),
    onSurfaceVariant: next(),
    inverseSurface: next(),
    inverseOnSurface: next(),
    outline: next(),
    outlineVariant: next(),
    primary: next(),
    onPrimary: next(),
    primaryContainer: next(),
    onPrimaryContainer: next(),
    primaryFixed: next(),
    primaryFixedDim: next(),
    primaryShelf: next(),
    secondary: next(),
    onSecondary: next(),
    secondaryContainer: next(),
    onSecondaryContainer: next(),
    secondaryFixed: next(),
    secondaryBrand: next(),
    secondaryShelf: next(),
    tertiary: next(),
    onTertiary: next(),
    tertiaryContainer: next(),
    onTertiaryContainer: next(),
    tertiaryFixed: next(),
    tertiaryBrand: next(),
    tertiaryShelf: next(),
    error: next(),
    onError: next(),
    errorContainer: next(),
    onErrorContainer: next(),
    cardBorder: next(),
    cardShelf: next(),
    answerSelectedFace: next(),
    answerCorrectFace: next(),
    answerIncorrectFace: next(),
    chosenFace: next(),
    tileBorder: next(),
    tileShelf: next(),
    lockedNodeFace: next(),
    lockedNodeIcon: next(),
    activeNodeShelf: next(),
    streak: next(),
    streakRim: next(),
    gem: next(),
    xp: next(),
    textMuted: next(),
    track: next(),
    primaryToneBorder: next(),
    primaryToneShelf: next(),
    primaryToneSurface: next(),
    secondaryToneBorder: next(),
    secondaryToneShelf: next(),
    tertiaryToneBorder: next(),
    tertiaryToneShelf: next(),
    tertiaryToneSurface: next(),
    dialogShelf: next(),
    scrim: next(),
    shadowInk: next(),
  );
}
